---

hermes_base_url: http://130.238.178.239:9000/api/0.1
hermes_user: dummy_user
hermes_token: my_token

summary_host: testuppmax
summary_user: arteria
summary_destination: /tmp/summaries/

remote_host: testuppmax
remote_user: arteria
remote_destination: /tmp/runfolders/
remote_sisyphus_location: /opt/arteria/arteria-siswrap-env/deps/sisyphus/sisyphus-latest


send_mail_to: example.mail.address@send.errors.to

runfolder_service_port: 10800
bcl2fastq_service_port: 10900
siswrap_service_port: 10700

# The service URL polled in the runfolder sensor:
runfolder_svc_urls:
  - http://testarteria1:10800

