---
name: "arteria-packs.gather_project_reports"
pack: "arteria-packs"
description: "Sync project reports from Irma to the summary host at the set intervals."
enabled: true

trigger:
    type: "core.st2.IntervalTimer"
    parameters:
      unit: hours
      delta: 2

action:
    ref: "arteria-packs.gather_project_reports"
