---
name: "snpseq-packs.gather_ngi_pipeline_reports"
pack: "snpseq-packs"
description: "Attempts to synchronize project reports from the ngi_pipeline at the set intervals."
enabled: true

trigger:
    type: "core.st2.IntervalTimer"
    parameters:
      unit: hours
      delta: 6

action:
    ref: "snpseq-packs.gather_ngi_pipeline_reports"


